import 'package:drop_down_list/model/selected_list_item.dart';
import 'package:flutter/material.dart';

class FixedLists {
  final List<SelectedListItem> listOfServices = [
    SelectedListItem(
      name: "Paint Job",
      value: "PJ",
    ),
    SelectedListItem(
      name: "Oil Change",
      value: "OC",
    ),
    SelectedListItem(
      name: "Tire Rotation",
      value: "TR",
    ),
    SelectedListItem(
      name: "Brake Inspection",
      value: "BI",
    ),
    SelectedListItem(
      name: "Transmission Service",
      value: "TS",
    ),
    SelectedListItem(
      name: "Battery Replacement",
      value: "BR",
    ),
    SelectedListItem(
      name: "Engine Tune-Up",
      value: "ET",
    ),
    SelectedListItem(
      name: "Alignment Check",
      value: "AC",
    ),
    SelectedListItem(
      name: "Cooling System Flush",
      value: "CSF",
    ),
    SelectedListItem(
      name: "Fuel System Cleaning",
      value: "FSC",
    ),
    SelectedListItem(
      name: "Detailing Service",
      value: "DS",
    ),
  ];

  final List<SelectedListItem> listOfCars = [
    SelectedListItem(name: "Toyota Camry", value: "TC"),
    SelectedListItem(name: "Honda Accord", value: "HA"),
    SelectedListItem(name: "Ford Mustang", value: "FM"),
    SelectedListItem(name: "Chevrolet Malibu", value: "CM"),
    SelectedListItem(name: "Nissan Altima", value: "NA"),
    SelectedListItem(name: "Hyundai Sonata", value: "HS"),
    SelectedListItem(name: "Kia Optima", value: "KO"),
    SelectedListItem(name: "Volkswagen Jetta", value: "VJ"),
    SelectedListItem(name: "Subaru Legacy", value: "SL"),
    SelectedListItem(name: "Mazda 6", value: "M6"),
    SelectedListItem(name: "BMW 3 Series", value: "B3"),
    SelectedListItem(name: "Mercedes-Benz C-Class", value: "MBC"),
    SelectedListItem(name: "Audi A4", value: "AA4"),
    SelectedListItem(name: "Lexus ES", value: "LE"),
    SelectedListItem(name: "Tesla Model 3", value: "TM3"),
    SelectedListItem(name: "Chevrolet Camaro", value: "CC"),
    SelectedListItem(name: "Dodge Charger", value: "DC"),
    SelectedListItem(name: "Jeep Wrangler", value: "JW"),
    SelectedListItem(name: "Ford Explorer", value: "FE"),
    SelectedListItem(name: "Toyota RAV4", value: "TR"),
    SelectedListItem(name: "Honda CR-V", value: "HCR"),
    SelectedListItem(name: "Nissan Rogue", value: "NR"),
    SelectedListItem(name: "Hyundai Tucson", value: "HT"),
    SelectedListItem(name: "Kia Sportage", value: "KS"),
    SelectedListItem(name: "Volkswagen Tiguan", value: "VT"),
    SelectedListItem(name: "Subaru Outback", value: "SO"),
    SelectedListItem(name: "Mazda CX-5", value: "MC5"),
    SelectedListItem(name: "Porsche 911", value: "P911"),
    SelectedListItem(name: "Jaguar F-Type", value: "JFT"),
    SelectedListItem(name: "Land Rover Range Rover", value: "LRRR"),
    SelectedListItem(name: "Volvo XC60", value: "VXC"),
    SelectedListItem(name: "Chrysler Pacifica", value: "CP"),
    SelectedListItem(name: "Buick Enclave", value: "BE"),
    SelectedListItem(name: "GMC Terrain", value: "GT"),
    SelectedListItem(name: "Acura MDX", value: "AMD"),
    SelectedListItem(name: "Infiniti QX60", value: "IQX"),
    SelectedListItem(name: "Fiat 500", value: "F500"),
    SelectedListItem(name: "Mini Cooper", value: "MC"),
    SelectedListItem(name: "Mitsubishi Outlander", value: "MO"),
    SelectedListItem(name: "Toyota Tacoma", value: "TT"),
    SelectedListItem(name: "Honda Ridgeline", value: "HR"),
    SelectedListItem(name: "Ford F-150", value: "FF"),
    SelectedListItem(name: "Chevrolet Silverado", value: "CS"),
    SelectedListItem(name: "Ram 1500", value: "R1500"),
    SelectedListItem(name: "Nissan Titan", value: "NT"),
    SelectedListItem(name: "Hyundai Santa Cruz", value: "HSC"),
    SelectedListItem(name: "Kia Seltos", value: "KS"),
    SelectedListItem(name: "Volkswagen ID.4", value: "VID"),
    SelectedListItem(name: "Tesla Model Y", value: "TMY"),
    SelectedListItem(name: "Rivian R1T", value: "R1T"),
    SelectedListItem(name: "Lucid Air", value: "LA"),
    SelectedListItem(name: "Ford Bronco", value: "FB"),
    SelectedListItem(name: "Chevrolet Blazer", value: "CB"),
    SelectedListItem(name: "Toyota 4Runner", value: "T4R"),
    SelectedListItem(name: "Honda Passport", value: "HP"),
    SelectedListItem(name: "Subaru Forester", value: "SF"),
    SelectedListItem(name: "Mazda CX-30", value: "MC30"),
    SelectedListItem(name: "Porsche Macan", value: "PM"),
    SelectedListItem(name: "Audi Q5", value: "AQ5"),
    SelectedListItem(name: "BMW X3", value: "BX3"),
    SelectedListItem(name: "Mercedes-Benz GLC", value: "MBG"),
    SelectedListItem(name: "Land Rover Discovery", value: "LRD"),
    SelectedListItem(name: "Volvo XC90", value: "VXC90"),
    SelectedListItem(name: "Chrysler 300", value: "C300"),
    SelectedListItem(name: "Buick LaCrosse", value: "BL"),
    SelectedListItem(name: "GMC Acadia", value: "GA"),
    SelectedListItem(name: "Acura TLX", value: "ATL"),
    SelectedListItem(name: "Infiniti Q50", value: "IQ50"),
    SelectedListItem(name: "Fiat 124 Spider", value: "F124"),
    SelectedListItem(name: "Mini Countryman", value: "MCC"),
    SelectedListItem(name: "Mitsubishi Eclipse Cross", value: "MEC"),
  ];
}
